### ISSUE TITLE
Last upgrade APK , does not allow to set URL instance

### ISSUE THREAD

**Issue by AnonymousWebHacker** [sschueller/peertube-android#260]
My peertube instance is totally decentralized, even without internet access.
The previous versions of the apk for android, let me set the URL of my instance, but with this new update, it no longer allows me.

All the people on my SNET who were using the app , over 1000 disappointed users.
Could it at least be added within the options, to be able to use an instance in spasification and not because of the list of federated instances on the internet?

![Screenshot_2021-02-04-13-33-05](https://user-images.githubusercontent.com/43164089/107079275-99b22180-67bd-11eb-9150-9dd400f5856a.png)

**Comment by sschueller** [comment]
You can specify any instance, just open the server book and type the URL in. It does not need to be in the federated list. If it does not let you enter your URL please let me know what it is (send me private email if you don't want to post it here). Which version are you running?

**Comment by AnonymousWebHacker** [comment]
@sschueller Thanks for answering.
My instance is on a SNET (they can't access it), no problems with that.
Stream: https: /peertube.azeroth.website
Version apk: 1.1.0-12d85f58

As I do not have internet to get the federated list of servers, I can not access there, and the apk no longer has the option to specify the URL of the server.

**Comment by sschueller** [comment]
The option to set URLs was moved into the server book (Second Icon Top right, three lines). In the address book click the plus at the bottom and add your server. You should be able to use it even without internet access. Can you confirm you can not enter the URL there?

**Comment by AnonymousWebHacker** [comment]
![Screenshot_2021-02-07-10-28-01](https://user-images.githubusercontent.com/43164089/107151260-9b035b80-692f-11eb-8410-94af6f78b30a.png)

**Comment by sschueller** [comment]
What device do you have? Very odd.

**Comment by AnonymousWebHacker** [comment]
LOL,
1- If I simply open the apk where the videos have to go, the apk closes without prior notice.
2 - Pressing `subscriptions` opened the list of servers well.

Android 6.0
Device: Huawei MYA-L13

Everything worked perfect, until this last update. At least I can continue using it

**Comment by AnonymousWebHacker** [comment]
It seems that it is because of the android version, I can't blame the programmer. Thank you for assisting me ;)

**Comment by AnonymousWebHacker** [comment]
By the way, I left to put the URL of the server, but the apk closes, and I still do not get the normal buttons to search, edit URL, or settings.

**Comment by AnonymousWebHacker** [comment]
Nothing, the apk closet and dont let me see video list

**Comment by AnonymousWebHacker** [comment]
Nothing, the apk closet and dont let me see video list

**Comment by AnonymousWebHacker** [comment]
Nothing, the apk closet and dont let me see video list

**Comment by sschueller** [comment]
Fixed in next release. 

https://github.com/sschueller/peertube-android/commit/06ace0d021733e608f917caae17188ebc71e413a

**Comment by redtux** [comment]
Thank you for the fix! 🚀 When will this be released on F-Droid? I am still experiencing this bug on a Xiaomi Mi MIX 2 phone.

**Comment by sschueller** [comment]
f-droid is usually 2-3 days behind.

**Comment by AnonymousWebHacker** [comment]
@sschueller Now that is fixed, thank you very much for that,....but,  only a problem happens, the app closes when trying to get the list of videos ;(

**Comment by sschueller** [comment]
> @sschueller Now that is fixed, thank you very much for that,....but, only a problem happens, the app closes when trying to get the list of videos ;(

Please try the latest version v1.4.0. I fixed a few more things.

**Comment by AnonymousWebHacker** [comment]
@sschueller  Fixeeeddd,!!!!!, really thank you very very much, excellent app :)
